### ISSUE TITLE
withExecutor causes Failsafe not to retry on exceptions in some cases

### ISSUE THREAD

**Issue by korri123** [failsafe-lib/failsafe#311] opened 2021-11-25 11:51 UTC
Hey, thank you for this great library! I've got an issue to report however.
```Java
@Test
void failsafeFail() throws InterruptedException {
    AtomicInteger counter = new AtomicInteger(0);
    Executor executor = Executors.newSingleThreadExecutor();
    Failsafe.with(RetryPolicy.builder()
                            .handle(RuntimeException.class)
                            .withMaxAttempts(2)
                            .build())
            .with(executor)
            .runAsync(() -> {
                if (counter.incrementAndGet() == 1)
                    throw new RuntimeException();
            });
    Thread.sleep(100);
    assertEquals(counter.get(), 2);
}
```
If you comment out `.with(executor)` the test case will work. When the case fails the method is run from `Functions.java#withExecutor(ContextualSupplier<R, T> supplier, Executor executor)` which calls `handleExecutableThrowable` which just throws the exception again. With the line commented out it uses a different code path that actually handles the exception.

**Comment by Tembrel** [comment] 2021-11-25 16:19
*Aside:* The overloading introduced by #221 isn't helping here. If you replace the line:
```
    Executor executor = Executors.newSingleThreadExecutor();
```
with
```
    ExecutorService executor = Executors.newSingleThreadExecutor();
```
the test passes as expected. Would it be terrible to use a longer name for the wrapping case, e.g., `withExecutor(Executor)`? I think a big ugly name is useful to warn users that they are getting special treatment.

**Comment by jhalterman** [comment] 2021-11-25 16:39
Thanks for filing this. I agree @Tembrel, a more explicit name wouldn't be bad. Thinking of other options though, since the intent here is to provide an `ExecutorService`, I wonder if `with(Executor)` should do an `instanceof` check and re-route `ExecutorService` instances to `with(ExecutorService)`. @Tembrel what do you think?

**Comment by Tembrel** [comment] 2021-11-25 17:05
How about adding those `instanceof` checks (for `ExecutorService` and `ScheduledExecutorService`) and __also__ provide explicit config methods `withExecutor(Executor)`, `withExecutorService(ExecutorService)`, and `withScheduler` (the latter could continue to be overloaded by `ScheduledExecutorService` and `Scheduler`)? Existing code using `with` would do the right thing by avoiding unnecessary wrapping, and new code could be explicit about intent, allowing users to request wrapping even if unneeded. (For example, one might want to preserve the pre-`instanceof`-check semantics of `with`.)

Explicit names are nice for those who read others' code; they can skip that momentary confusion that occurs when encountering a line with no type information:
```java
    .with(CONNECT_POOL)
```
You can argue that `CONNECT_POOL` isn't a great name, but it's not an unrealistic one. I'd rather see this in that case:
```java
    .withExecutorService(CONNECT_POOL)
```
Maybe an explicit name like `withPlainExecutor(Executor)` would keep people from using that method accidentally.

**Comment by jhalterman** [comment] 2021-11-26 22:03
3.0.2 is released with a fix for this regression.

**Closed by jhalterman** 2021-11-26 22:03 UTC

**Comment by korri123** [comment] 2021-11-27 00:12
Amazing, thank you!
