### ISSUE TITLE
Cancellation on timeout when using Failsafe's getStageAsync

### ISSUE THREAD

**Issue by afds** [failsafe-lib/failsafe#273] opened 2021-04-25 06:56 UTC
I see there is some confusion about FailSafe's Timeout policy. Mine case is a bit different and related to `getStageAsync(CheckedSupplier<? extends CompletionStage<T>>)` usage.

I'm expecting that `CompletableFuture` that I provide in this supplier will be cancelled if timeout triggers.
Please [see this gist](https://gist.github.com/afds/2018a2c18c7c164d345b03ae43c063bf) for example case. I'm expecting that "Cancelled!" will be printed, but it is not.

Could it be that this is a bug or is this valid and expected behaviour?

failsafe version: 2.4.0

**Comment by afds** [comment] 2021-04-25 06:58
Slightly related issues
https://github.com/jhalterman/failsafe/issues/271
https://github.com/jhalterman/failsafe/issues/263
https://github.com/jhalterman/failsafe/issues/258

**Comment by Tembrel** [comment] 2021-04-25 14:09
This is valid and expected behavior, though it might seem surprising: The `getStageAsync` method takes something that supplies a `CompletionStage`, which doesn't have a `cancel` method. So even though in this case you are supplying a `CompletableFuture` &mdash; which, because it implements `Future`, __does__ have a `cancel` method &mdash; the Failsafe machinery will never call your overridden `cancel` method.

For a long discussion on the design of the Timeout policy that touches on these points, see issue #169.

**Comment by Tembrel** [comment] 2021-04-25 16:43
At the risk of [repeating myself](https://github.com/jhalterman/failsafe/issues/263#issuecomment-684133943) egregiously, if you want your Failsafe tasks to stop running after timeout exceeded, make them responsive to interruption or use the execution context to check for cancellation. With `getStageAsync`, only the latter option is practical.

[Here's a minimal rewrite](https://gist.github.com/Tembrel/20bee82ee13ff305168a39cbac6e2130) of @afds's gist that uses the execution context to make the task responsive to timeout. Instead of a single 5 second sleep, it checks every 200ms to see if the context has seen a cancellation request (by timeout being exceeded, in this case).

Note that the `InterruptedException` clause is __not__ reached, because the self-call to `cancel(true)` just sets the interrupt status; it's not in the middle of a sleep or other blocking operation.

Note that in practice one would use something like `CompletableFuture.supplyAsync(() -> ...)` to supply the stage, resulting in a somewhat more compact form:
```java
final CompletableFuture<Integer> call = Failsafe.with(timeout)
    .getStageAsync(ctx -> CompletableFuture.supplyAsync(() -> {
	try {
	    long POLL_MILLIS = 200L;
	    long millisRemaining = 5_000L;
	    while (millisRemaining > 0) {
		if (ctx.isCancelled()) {
		    log("Cancelled!");
		    return 2;
		}
		Thread.sleep(POLL_MILLIS);
		millisRemaining -= POLL_MILLIS;
	    }
	    log("Work completed!");
	    return 1;
	} catch (InterruptedException ignored) {
	    log("Interrupted!");
	    return 3;
	}
    }));
```
The effect is the same, though.

**Comment by afds** [comment] 2021-04-26 04:58
Thanks for reply. However I don't see how this is practical with `getStageAsync(...)`, in real life I would expect to give it a chain of `CompletableFutures` with Netty's future at the end for example. Having additional thread that polls `ExecutionContext` status is overkill in this case. I think that falling back to Java's `CompletableFuture.orTimeout(...)` would be best option for me.

**Comment by Tembrel** [comment] 2021-04-26 14:47
`CompletableFuture.orTimeout` just forces exceptional completion with a `TimeoutException` if the future doesn't complete normally within the timeout interval. It does __not__ interrupt (or otherwise stop) the execution of whatever stages are running at the point of timeout. In particular, if you're doing long-running computations or I/O operations, they will continue to run even as the chain of futures completes (exceptionally) within the timeout interval.

That __might__ be sufficient for your purposes, but given that you've posted this as a Failsafe issue, it seems unlikely. Presumably you're interested in Failsafe as a way to retry operations in a controlled and safe manner. Leaving operations running while you repeatedly retry them runs the risk of exhausting system resources in an uncontrolled, unsafe way.

So let's assume you have a chain of completion stages that should __not__ be allowed to run indefinitely: You need those stages to be aware of the possibility that the Failsafe execution they are participating in will be cancelled (e.g., due to a timeout). As I've [suggested elsewhere](https://github.com/jhalterman/failsafe/issues/263#issuecomment-684133943), you can do this in a way that doesn't force explicit knowledge of Failsafe within your own code. It __does__ mean that you have to think hard about where to check cancellation status, but checking (reading a boolean value) is inexpensive: You can do it inside a loop without a performance penalty. You only need another thread to poll cancellation status in cases where you are blocking interruptibly with no time limit and want to check status while blocked.

### Alternative 1

Consider inverting the responsibility using Failsafe's [asynchronous API support](https://jodah.net/failsafe/async-api/). This would allow you to control Failsafe execution within your asynchronous stages. 

### Alternative 2

Consider containing the Failsafe logic to one stage at a time, if that's at all meaningful in your situation. For example, maybe the only the last stage (you mentioned Netty) needs retry/circuit-breaker logic.

### Alternative 3

Failsafe is so far maintaining compatibility with Java 8 (for which I'm grateful), but if you can use `CompletableFuture.orTimeout`, it means you are using Java 9 or later. So you __might__ be able to write a [custom subclass of `CompletableFuture` that overrides `cancel`](https://stackoverflow.com/a/60931165) to do any cleanup needed, but it sounds very tricky, and I'm not even sure that it would work. (Does `orTimeout` cause `cancel(...)` to be called on timeout?)

**Comment by afds** [comment] 2021-04-26 19:15
It really depends on the use cases. I understand your concern about potential exhaustion of system resources. There can be protection on lower level as well.

Let's take this policy composition as an example: (Fallback, CircuitBreaker, Timeout, Operation). I want to open circuit breaker as soon as there is some problem with primary operation, this could be remote server unavailability and/or increased timeout that we can't afford. I want to fallback as soon as possible, not waiting for primary operation to complete. And I want to respond to my client as soon as possible.

Sorry for initial confusion, this is the code that I was referring to as something similar to Java's `CompletableFuture.orTimeout(...)` it does `cancel(...)` call.

```java
class Timeout {
    ...
    public <T> CompletableFuture<T> apply(final CompletionStage<T> completionStage) {
        final CompletableFuture<T> cf = completionStage.toCompletableFuture();
        if (canCancel()) {
            return Futures.cancelOnTimeout(cf, canInterrupt(), getTimeout().toNanos(),
                                           TimeUnit.NANOSECONDS)
                          .exceptionally(t -> {
                              if (t instanceof CancellationException) {
                                  throw new TimeoutExceededException(this, t);
                              }
                              throw new CompletionException(t);
                          });
        }
        return Futures.orTimeout(cf, getTimeout().toNanos(), TimeUnit.NANOSECONDS)
                      .exceptionally(t -> {
                          if (t instanceof TimeoutException) {
                              throw new TimeoutExceededException(this, t);
                          }
                          throw new CompletionException(t);
                      });
    }
    ...
}

class Futures {
    ...
    public static <T> CompletableFuture<T> cancelOnTimeout(final CompletableFuture<T> future,
                                                           final boolean mayInterruptIfRunning,
                                                           final long timeout,
                                                           final TimeUnit unit) {
        requireNonNull(future);
        requireNonNull(unit);
        if (!future.isDone()) {
            future.whenComplete(new Canceller(Delayer.delay(new Cancel(future, mayInterruptIfRunning), timeout, unit)));
        }
        return future;
    }
    ....
    static final class Cancel implements Runnable {

        final CompletableFuture<?> f;
        final boolean mayInterruptIfRunning;

        Cancel(final CompletableFuture<?> f, final boolean mayInterruptIfRunning) {
            this.f = f;
            this.mayInterruptIfRunning = mayInterruptIfRunning;
        }

        @Override
        public void run() {
            if (f != null && !f.isDone()) {
                f.cancel(mayInterruptIfRunning);
            }
        }
    }
    ...
}
```

**Comment by Tembrel** [comment] 2021-04-26 19:41
Sounds like you have a plan for this case: You'll wrap your basic call with custom timeout machinery, then wrap that with a CircuitBreaker, and finally wrap that with a Fallback. No Failsafe Timeout needed.

In general, though, it's better to use cancellation-aware tasks with Failsafe, if at all possible.

All these issues on Timeout suggest that we need documentation and examples for Timeout that explain its limitations clearly, so no one else is tempted to create further issues along these lines.

**Comment by jhalterman** [comment] 2021-08-09 05:48
Since it seems like this discussion is resolved, closing. Feel free to reopen if needed.

**Closed by jhalterman** 2021-08-09 05:48 UTC
Labels: question
